version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
    - checkout

    - restore_cache:
        keys:
        - sbt-scala-cache-{{ checksum "build.sbt" }}

    - run: sbt clean test:compile

    - save_cache:
        paths: ["/home/circleci/.m2", "/home/circleci/.ivy2/cache", "/home/circleci/.coursier/cache", "/home/circleci/.sbt/launchers", "/home/circleci/.cache/coursier"]
        key: sbt-scala-cache-{{ checksum "build.sbt" }}

    - run: sbt test